name: Increase App Version - minor
on:
  push:
    branches:
      - patch/**
jobs:
  increase-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install Dependencies
        run: npm install
      - name: Patch version
        run: npm version patch
      - name: Push new verison
        run: git push
      env:
        # The secret is passed automatically. Nothing to configure.
        github-token: ${{ secrets.GITHUB_TOKEN }}